Refactor
mariklolik/os_sem2 pull request #2
Opened 2023-12-22 11:12 UTC by mariklolik

Исправил табуляцию в 1 и 2.1. Добавил 2.2

2023-12-30 13:42 UTC, ksilobait requested changes

2023-12-30 13:42 UTC, ksilobait commented on threads/lab1-3/b.c
> +        perror("Malloc failed.\n");
Не нужно одновременно использовать и `perror`, и `printf("%s", strerror(err))`, эти методы работают одинаково (первое проще использовать, второе более гибкое)

2023-12-30 13:42 UTC, ksilobait commented on OS_2.2/queue-cond-var.c
> +        return 0;
Странно видеть в двух симметричных методах разные подходы к блокировкам (if с выходом и while без выхода)

2023-12-30 13:42 UTC, ksilobait commented on OS_2.2/queue-example.c
Зачем этот файл тут?
И так файлов много, сложно разобраться, как все это запускать, еще и лишние файлы находятся

2023-12-30 13:42 UTC, ksilobait commented on OS_2.2/queue-semaphore.c
> +        sem_post(&semaphore);
Ничего в очереди не изменилось, но происходит оповещение всех, кто заснул на семафоре - нужен здесь другой подход: два семафора ("число свободных мест" и "число занятых мест") и мутекс для блокирования критической секции; семафор не используют вместо мутекса для блокировок критических секций

2023-12-30 13:43 UTC, ksilobait commented on threads/lab1-3/b.c
> +        perror("Malloc failed.\n");
(исправлять не нужно, просто замечание)

2024-01-17 19:17 UTC, mariklolik commented on OS_2.2/queue-cond-var.c
> +        return 0;
поменял

2024-01-17 19:17 UTC, mariklolik commented on OS_2.2/queue-example.c
убрал

2024-01-17 19:17 UTC, mariklolik commented on OS_2.2/queue-semaphore.c
> +        sem_post(&semaphore);
поменял

2024-01-18 16:33 UTC, merged